### PR TITLE
Use patch library instead of Reflex.Patch.*

### PR DESCRIPTION
**Pull request by xplat**

### CODE REVIEW

**Comment by Ericson2314** [comment]
I think we might have more things to report for https://github.com/ndmitchell/hlint/issues/818

**Comment by Ericson2314** [comment]
Old failing CI for reference https://travis-ci.org/reflex-frp/reflex/builds/635019574?utm_source=github_status&utm_medium=notification

**Comment by Ericson2314** [comment]
Yuck, I just have no idea how to fix this hlint thing, so merging anyways.

**Comment by 3noch** [comment]
Can't you just disable the lint in that file with an "hlint pragma"? See Ignoring Hints in https://hackage.haskell.org/package/hlint-1.7/src/hlint.htm

**Comment by Ericson2314** [comment]
@3noch What's really annoying is that it works locally due to the freeze file banning the bad version.

**Pull request merged**
