### PR TITLE
Clarify difference between Incremental and Dynamic

### PR DESCRIPTION
**Pull request by eskimor**
Btw. do you have any code at hand making use of Incrementals, I get a feeling it could help simplify some code of mine, but a usage example would really help.

### CODE REVIEW

**Comment by ryantrinkle** [comment]
You can see a use of an incremental [here](https://github.com/reflex-frp/reflex/blob/develop/src/Reflex/EventWriter.hs#L133), but I'm afraid it's not likely to simplify anything until we've got a much nicer set of combinators for Incrementals; right now, Incrementals are pretty much only used for performance-critical code, via mergeIncremental.  The primary use case is to make small changes to a large merge.

**Comment by ryantrinkle** [comment]
I think we should probably do this documentation change the other way around - most users shouldn't need to understand what an Incremental is at all, so I don't want to send users trying to understand Dynamic over to Incremental first.  Do you think you could reword this, perhaps to explain in Incremental's docs that it's a generalization of Dynamic?

**Comment by eskimor** [comment]
Thank you!
Better now?

**Comment by ryantrinkle** [comment]
Looks great, thanks!

**Pull request merged**
