### PR TITLE
Add Monoid and Semigroup instances

### LINKED ISSUE #141: Monoid/Semigroup instances for PostBuildT
where `<>` == `>>`. This is handy in same cases for abstractions and simply because the precedence of these operators is different.

### PR DESCRIPTION
**Pull request by 3noch**
Fixes #141

### CODE REVIEW

**Comment by 3noch** [comment]
Of note: https://mail.haskell.org/pipermail/haskell-cafe/2017-March/126605.html

**Comment by 3noch** [comment]
Using `Alternative` for any of the monads in Reflex seems highly dubious. However, using `Monoid (m a)` seems seems possible.

**Comment by ryantrinkle** [comment]
Thanks!

**Comment by Ericson2314** [comment]
The mailing list post there pointed out there's multiple instances and neither is necessarily better, hmm.

**Comment by ryantrinkle** [comment]
My recollection was that that was more or less resolved

**Comment by 3noch** [comment]
Some more argumentation was made in November regarding ReaderT: https://mail.haskell.org/pipermail/libraries/2017-November/028312.html

**Comment by 3noch** [comment]
And `IO` has this instance: https://hackage.haskell.org/package/base-4.10.1.0/docs/Prelude.html#t:Monoid

**Comment by ryantrinkle** [comment]
Actually, looking at this code, there *is* one more thing we should change: we should also lift mconcat, sconcat, and stimes, since the underlying implementations may be more efficient.

**Comment by 3noch** [comment]
Good call. I can add that this weekend.

**Comment by ryantrinkle** [comment]
Sounds good :)

**Pull request merged**
