### PR TITLE
Less unsafeCoerce

### PR DESCRIPTION
**Pull request by treeowl**
Get rid of most unnecessary uses of `unsafeCoerce`. Several of the ones that remain are removed by #320.

### CODE REVIEW

**Comment by treeowl** [comment]
Big question: how should I name the `RIO` module? I don't want it getting mixed up with the one from `rio`, since it's pretty much internal. I don't care myself.

**Comment by treeowl** [comment]
@Ericson2314 I was quite unable to get anything good out of the manual `case` on `Coercion` idea. For whatever reason, I couldn't get GHC to infer the right coercion flow. But I was able to dramatically reduce the type annotations I was using before.

**Comment by Ericson2314** [comment]
@treeowl I think you forget to add the RIO module. OTOH I think there might be another way around the `RIO` stuff.

**Comment by treeowl** [comment]
@Ericson2314 Whoops, fixed that. The only way I see around `RIO` is to do something like `DynamicS x p = Dynamic x (Behavior x (PatchTarget p)) p`. That might do the trick, but it doesn't exactly improve clarity.

**Comment by Ericson2314** [comment]
@treeowl Yeah and also if other roles depend on `BehaviorM` their's no opportunity to provide your own coercion to prove a non-nominal role.

**Comment by cgibbard** [comment]
Wait, what? I see exposed-modules: Control.Monad.RIO, and I see an import
of that module, but I don't see that module itself.

**Comment by Ericson2314** [comment]
@cgibbard see I wrote that above :)  @treeowl I think you meant to push but didnt'?

**Comment by treeowl** [comment]
Oh crud. Yeah, I forgot to push. Actually fixed now, I believe!

**Comment by ryantrinkle** [comment]
To avoid confusion with https://github.com/commercialhaskell/rio/blob/10d0bd8c6b03035504c5c086dc90ad85cdb0b914/rio/src/RIO/Prelude/RIO.hs#L38, I think it would be better for us to choose an uglier name for our reader-over-IO.  In particular, our goals are pretty different: RIO is aimed at improving the elegance of user code, whereas this reader-over-IO is simply a hack around the role system's inability to express quite the right thing.  Given that one can't be substituted for the other (RIO doesn't fix the role issue, and this thing doesn't help with any of RIO's goals), I think it would be better to use a different, uglier name.  I'd propose `ReaderT_IO` or `ReaderIO` just so it's blatant what's going on.  Ideally, if GHC improves the role system in the future, this would go away.

**Comment by treeowl** [comment]
@ryantrinkle I've renamed the module and type as you requested.

**Pull request merged**
