### PR TITLE
phadej's haskell-ci setup; Bump to v0.6.2.2; Update version bounds

### PR DESCRIPTION
**Pull request by ali-abrar**

### CODE REVIEW

**Comment by phadej** [comment]
One could add
```
benchmarks: False
```

to `cabal.haskell-ci`, which would help CI to get to the end with a cold cache.

---

That's something I need to think about for `haskell-ci`, how to make cold cache builds fit into time limits.

**Comment by saulzar** [comment]
> Disallowing sources: hvr-ghc
> To add unlisted APT sources, follow instructions in https://docs.travis-ci.com/user/installing-dependencies#Installing-Packages-with-the-APT-Addon

Did Travis just change this as of right now?

**Comment by ali-abrar** [comment]
As far as I can tell, yes. I haven't made any relevant changes.

**Comment by phadej** [comment]
I think it’s related to using `dist: bionic`

**Comment by phadej** [comment]
See also https://github.com/ekmett/lens/pull/879 for some Q&A related to GHCJS job

**Comment by saulzar** [comment]
Well this seems to work okay for GHCJS, but it still times out on all the normal GHC builds..

**Pull request merged**
