### PR TITLE
Renames MonadAdjust and moves it to its own module.

### PR DESCRIPTION
**Pull request by dalaing**
This also brings the collection management functions across from `reflex-dom` - there is a companion PR in `reflex-dom` dealing with this [here](https://github.com/reflex-frp/reflex-dom/pull/163).

### CODE REVIEW

**Comment by ryantrinkle** [comment]
Let's do something like this: https://gist.github.com/ryantrinkle/82ba8e95cc2ddd0bdf2c54c7317c645c

**Comment by dalaing** [comment]
I'm trying to work out how to do that without a cyclic import :/

**Comment by dalaing** [comment]
I might move Adjustable back into Reflex.Class, but have the list function in Reflex.Adjustable.Base? or something like that?

**Comment by dalaing** [comment]
The current plan is to move `Adjustable` back into `Reflex.Class` and to move the collection management functions into `Reflex.Collection` - if I'm doing that, should I move `sortableList` from `Reflex.Widget.Basic` into `Reflex.Collection` as well?

**Comment by ryantrinkle** [comment]
Hmm, maybe we should bite the bullet and break which module it's in.  As long as we make sure to re-export from Reflex, most people probably wan't hit it (I think importing Reflex.Class itself directly is probably not super-common).  I don't know how to do a smooth transition for the actual move.

**Pull request merged**
