### PR TITLE
Move Travis to 8.2.1

### PR DESCRIPTION
**Pull request by gliptak**
Build failing at https://travis-ci.org/reflex-frp/reflex/jobs/279012295

https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/ghc

### CODE REVIEW

**Comment by ryantrinkle** [comment]
Do you know if this prevents it from failing?

**Comment by ryantrinkle** [comment]
Ah, nevermind; I see your other PR that addresses the failure.

**Comment by gliptak** [comment]
Waiting for https://travis-ci.org/reflex-frp/reflex/jobs/279031560 to complete.

**Comment by ryantrinkle** [comment]
Thanks!

**Comment by gliptak** [comment]
Still fails at https://travis-ci.org/reflex-frp/reflex/jobs/279032250

Pulling in /nix/store/1q769ksp1jdqd5wj2i04ypzgbwmyalki-these-0.7.3-r4.cabal needs these-0.7.4

**Pull request merged**
