### PR TITLE
Reflex.Time: Add throttle

### PR DESCRIPTION
**Pull request by ali-abrar**
@cgibbard was too lazy to make a PR so I'm doing it with his code.

### CODE REVIEW

**Comment by mulderr** [comment]
Just the other day I was thinking I need something exactly like that to throttle scroll events but couldn't immediatelly figure out how to do it. This is great!

**Comment by ali-abrar** [comment]
@mulderr `debounce` or `batchOccurrences` might also do something like what you're looking for. The difference between `debounce` and `throttle` is that `debounce` does not allow the initial event through until the cooldown time has elapsed, whereas `throttle` lets the initial event through immediately and then applies the cooldown to subsequent events (until enough time has elapsed without events that we consider the next one an initiating event).

For example, if you had `debounce 1 =<< button "click me"`, and clicked on it rapidly, you'd receive no events until you stopped clicking for one second. With `throttle` you'd get the first click, and then another when you stop clicking for one second.

**Comment by cgibbard** [comment]
(Sorry Ali for taking too long on this, haha!)

There's another difference between throttle and debounce, that throttle shouldn't wait until you stop clicking before letting another occurrence through, it should only wait for the timeout to elapse before firing again.

We could also generalise this code a little further with regard to what happens when multiple occurrences happen while throttled (i.e. debounce is to batchOccurrences what throttle is to something).

**Comment by mulderr** [comment]
In that case, I think this *is* exactly what I need. I only care about the last occurrence, I don't want it too often because it may cause DOM manipulation but I also don't want to wait until it settles like `debounce` because things should update more or less continuously.

**Pull request merged**
