### PR TITLE
Fix 7.10 build

### PR DESCRIPTION
**Pull request by luigy**

### CODE REVIEW

**Comment by luigy** [comment]
Fixes #99

**Comment by cgibbard** [comment]
Looks good to me -- but maybe merge to develop rather than the branch I made?

**Comment by luigy** [comment]
I merged it to your branch since it depended on your commits :)
We'll have to wait for ryan to get this merged onto develop

**Comment by lynnard** [comment]
Awesome this works for me!

**Comment by hansroland** [comment]
This works also for me and I closed my issue #99 and PR #115. Many thanks!

**Pull request merged**
