### PR TITLE
Use Data.Filtrable instead of FunctorMaybe

### PR DESCRIPTION
**Pull request by ali-abrar**
Based on the discussion in #19

### CODE REVIEW

**Comment by ali-abrar** [comment]
I did a little looking around to see if any other package would be better for what we need and didn't find anything, but suggestions are certainly welcome.

**Comment by spl** [comment]
:+1:

**Comment by 3noch** [comment]
Are we aiming for American or English spellings? `Filtrable` is not the American spelling.

**Comment by spl** [comment]
I didn't even realize “Filtrable” was a spelling in any dialect. Nonetheless, I think the issue that @ali-abrar is proposing a solution to is the singular use of `FunctorMaybe` instead of some more common or more standard type class. I wouldn't be against using `Filtrable` because it doesn't fit my expected spelling.

I think a better question is: what benefit would `reflex` get from using `filtrable` instead of `FunctorMaybe`? If it was a widely used package, then that would mean more people would be familiar with it and/or be able to use it in other places. Unfortunately, this is not the case according to [its reverse dependencies](http://packdeps.haskellers.com/reverse/filtrable). Still, I like the fact that somebody created a package that could potentially become more common.

**Comment by 3noch** [comment]
@spl Ah, I didn't even look at the diff so I didn't realize he was pulling in a dependency with that name! In that case, there's not much of a choice. Carry on!

**Comment by ali-abrar** [comment]
I'm not completely satisfied with the use of this library either. I'm still looking around to see if there's something else we could use. `Data.Witherable` has been recommended by a few people, but the `Traversable` requirement it imposes is something we can't meet here (and, despite the recommendations, witherable's reverse dependencies reveal that it isn't really that much more popular than Filtrable).

**Comment by ryantrinkle** [comment]
It would be great to replace FunctorMaybe with something more general - or at least more widely used - but it looks like Filtrable probably isn't that thing.  I'm going to close this, but hopefully another alternative will appear eventually.

**Pull request closed without merging**
